apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "mongo-pv-local" 
  resources:
    requests:
      storage: 5Gi  