apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjMk1qZ3pOamM0TWl3aWFXRjBJam94TnpZeU9ETTJOemd5ZlEuZ1psTFNWOXpTYXVnOVRRZ216Q1FockdFdU9CUy1MWXdMZUtEdnZiMDZRdw==
